server.port = 8080
spring.application.name = "ecommers"

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommers
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.devtools.restart.enabled=true

#security
spring.security.user.name=user
spring.security.user.password=root